 // eslint-disable-next-line import/prefer-default-export
 export const educationsDB = [{
         id: 1,
         course: "Doctoral's Degree in Computer Science",
         startedAt: "2019",
         finishedAt: "2023",
         university: {
             name: "UFBA - Federal University of Bahia",
             url: "https://computacao.ufba.br/pt-br/programa-de-pos-graduacao-em-ciencia-da-computacao",
         },
         researchLine: "Recommender Systems",
         brand: "ufba.png",
         curriculum: [
             "Graphs and Algorithms (Master's Degree)",
             "Scientific Seminaries (Master's Degree)",
             "Research Fundamentals of Computer Science II",
             "Topics in Computer Intelligence II (Master's Degree)",
             "Topics in Computer Intelligence III (Master's Degree)",
             "Topics in Information Systems and Web I (Master's Degree)",
             "Artifical Intelligence",
             "Web Systems",
             "Oriented Research",
             "Oriented Teaching Internship",
             "Qualification Exam",
             "Annual Assessment Seminars",
             "Final Paper",
             "Preparation of the Doctoral Thesis",
         ],
     },
     {
         id: 2,
         course: "MBA Executive in Business Analytics",
         startedAt: "2021",
         finishedAt: "2022",
         university: {
             name: "IPOG - Postgraduate Institute",
             url: "https://ipog.edu.br/",
         },
         researchLine: "Defining",
         brand: "ipog.png",
         curriculum: ["Data Driven Strategic Management",
             "Leadership in Innovation and Digital Transformation",
             "Business Intelligence and Business Analytics",
             "Data Analysis and Science",
             "Agile Management in Data Driven Projects and Products",
             "Python for Data Science",
             "Cloud Computing, Architecture and Data Engineering",
             "Startup Experience - Launch",
             "Artificial Intelligence as a Competitive Advantage",
             "Data-Driven Marketing Management",
             "Probability and Statistics for Business",
             "Integral Development of Human Potential",
         ],
     },
     {
         id: 3,
         course: "Postgraduate in Computer Forensics and Information Security",
         startedAt: "2021",
         finishedAt: "2022",
         university: {
             name: "IPOG - Postgraduate Institute",
             url: "https://ipog.edu.br/",
         },
         researchLine: "Defining",
         brand: "ipog.png",
         curriculum: ["Principles of Criminalistics and Introduction to Computer Forensics",
             "Forensic Analysis of the Windows Operating System",
             "Forensic Analysis of the LINUX Operating System",
             "Special Topics: Cryptocurrencies, Darkweb, IoT and Forensic Readiness",
             "Storage Media Expertise",
             "Expertise in Portable and Mobile Computing Equipment",
             "Exams in Malware and Anti-Forensic Techniques",
             "Expertise in Internet Sites and Related to Child and Youth Pornography",
             "Forensic Practices: Preparation of Reports and Opinions, and Technical Assistance",
             "Cryptography and Cryptanalysis",
             "Cyber Security and Intelligence",
             "Digital Imaging Skills",
         ],
     },
     {
         id: 4,
         course: "Postgraduate in Criminal Science and Forensic Sciences",
         startedAt: "2019",
         finishedAt: "2021",
         university: {
             name: "UNIT - Tiradentes University",
             url: "https://www.unit.br/",
         },
         researchLine: "Digital Chain of Custody",
         brand: "unit.png",
         curriculum: ["Place of Crime",
             "Legal Medicine",
             "Introduction to Criminalistics",
             "Forensic Psychology",
             "Forensic Ballistics",
             "Legislation Applied to Criminalistics",
             "Documentoscopy",
             "Papiloscopy",
             "Scientific methodology",
             "Bombs, Explosives and Fuels",
             "Forensic Biology",
             "Forensic Dentistry",
             "Forensic Anthropology",
             "Forensic Genetics",
             "Drug of abuse analysis",
             "Environmental expertise",
             "Computer Forensics",
             "Forensic Engineering",
             "Forensic Entomology",
             "Traffic-accidents",
             "Forensic Toxicology",
             "Completion Seminars",
             "Monography",
         ],
     },
     {
         id: 5,
         course: "Master's Degree in Computer Science",
         startedAt: "2017",
         finishedAt: "2019",
         university: {
             name: "UFBA - Federal University of Bahia",
             url: "https://computacao.ufba.br/pt-br/programa-de-pos-graduacao-em-ciencia-da-computacao",
         },
         researchLine: "Recommender Systems",
         brand: "ufba.png",
         curriculum: ["Algorithms and Graphs",
             "Scientific Seminars",
             "Fundamentals of Research in Computer Science I",
             "Topics in Computational Intelligence II",
             "Topics in Information Systems and WEB I",
             "Topics in Computational Intelligence III",
             "Oriented Research",
             "Oriented Teaching Internship",
             "Master's Proposal Project",
             "Defense of Master's Proposal",
             "TCC",
         ],
     },
     {
         id: 6,
         course: "MBA in Database Administration",
         startedAt: "2014",
         finishedAt: "2016",
         university: {
             name: "Fanese - Faculty of Business and Administration of Sergipe",
             url: "https://fanese.edu.br/",
         },
         researchLine: "Data Warehouse",
         brand: "fanese.png",
         curriculum: ["Database Fundamentals",
             "Network Infrastructure",
             "Operating Systems Infrastructure and Server Administration",
             "Ethics and Social and Environmental Responsibility",
             "Interpersonal Relations",
             "Database Architecture and Administration I (SQL Server)",
             "Database Architecture and Administration II (Oracle)",
             "Backup and Restore Procedures I (SQL Server)",
             "Backup and Restore Procedures II (Oracle)",
             "Scientific Research Methodology I",
             "Database Application Optimization",
             "Certification Preparation (MCITP)",
             "Database Security and Auditing",
             "Database Architecture and Management III (PostgreSQL)",
             "Business Intelligence and DataWarehouse",
             "Data Mining",
             "Scientific Research Methodology II",
             "Preparation for Certification (OCA)",
             "Replication and High Availability", "TCC",
         ],
     },
     {
         id: 7,
         course: "Web Systems",
         startedAt: "2112",
         finishedAt: "2014",
         university: {
             name: "UNIT - Tiradentes University",
             url: "https://www.unit.br/",
         },
         researchLine: "",
         brand: "unit.png",
         curriculum: ["Mathematical logic",
             "Introduction to informatics",
             "Introduction to Web Programming",
             "Web Standards",
             "Computer Organization and Architecture",
             "Scientific methodology",
             "Investigative Practices I",
             "Software Engineering I",
             "Web Technology",
             "Operational systems",
             "Process Organization",
             "Extensionist Practices I",
             "Data Structure I",
             "Database I",
             "Software Engineering II",
             "Web Technology II",
             "Data Structure I",
             "Database I",
             "Software Engineering II",
             "Computer Networks I",
             "Operational systems",
             "Data Structure I",
             "Software Engineering II",
             "Security in Web Applications",
             "Project Management",
             "Special Topics (Optional)",
             "Process Organization",
             "Data Structure II",
             "Web Technology III",
             "Web Project I",
             "Web Project II",
             "Internship in Web Development",
             "Application Architecture Project",
         ],
     },
 ];