 // eslint-disable-next-line import/prefer-default-export
 export const educationsDB = [{
         id: 1,
         course: "Doctoral's Degree in Computer Science",
         startedAt: "2019",
         finishedAt: "2023",
         university: {
             name: "UFBA - Federal University of Bahia",
             url: "https://computacao.ufba.br/pt-br/programa-de-pos-graduacao-em-ciencia-da-computacao",
         },
         researchLine: "Recommender Systems",
         brand: "ufba.png",
         curriculum: ["Algoritmos e Grafos (Mestrado)",
             "Seminários Científicos (Mestrado)",
             "Fundamentos de Pesquisa em Ciência da Computação II",
             "Tópicos em Inteligência Computacional II (Mestrado)",
             "Tópicos em Inteligência Computacional III (Mestrado)",
             "Tópicos em Sistemas de Informação e WEB I (Mestrado)",
             "Inteligência Artificial",
             "Sistemas WEB",
             "Pesquisa Orientada",
             "Estágio Docente Orientado",
             "Exame de Qualificação",
             "Seminários de Avaliação Anuais",
             "Trabalho de Conclusão",
             "Elaboração da Tese de Doutorado",
         ],
     },
     {
         id: 2,
         course: "MBA Executive in Business Analytics",
         startedAt: "2021",
         finishedAt: "2022",
         university: {
             name: "IPOG - Postgraduate Institute",
             url: "https://ipog.edu.br/",
         },
         researchLine: "Defining",
         brand: "ipog.png",
         curriculum: ["Gestão Estratégica Data Driven",
             "Liderança em Inovação e Transformação Digital",
             "Inteligência de Negócios e Business Analytics",
             "Análise e Ciência de Dados",
             "Gestão Ágil em Projetos e Produtos Data Driven",
             "Python para Ciência de Dados",
             "Cloud Computing, Arquitetura e Engenharia de Dados",
             "Startup Experience - Launch",
             "Inteligência Artificial como Vantagem Competitiva",
             "Gestão de Marketing Guiada por Dados",
             "Probabilidade e Estatística para Negócios",
             "Desenvolvimento Integral do Potencial Humano",
         ],
     },
     {
         id: 3,
         course: "Postgraduate in Computer Forensics and Information Security",
         startedAt: "2021",
         finishedAt: "2022",
         university: {
             name: "IPOG - Postgraduate Institute",
             url: "https://ipog.edu.br/",
         },
         researchLine: "Defining",
         brand: "ipog.png",
         curriculum: ["Princípios de Criminalística e Introdução à Computação Forense",
             "Análise Forense do Sistema Operacional Windows",
             "Análise Forense do Sistema Operacional LINUX",
             "Tópicos Especiais: Criptomoedas, Darkweb, IoT e Forensic Readiness",
             "Perícias em Mídias de Armazenamento",
             "Perícias em Equipamentos Computacionais Portáteis e de Telefonia Móvel",
             "Exames em Malwares e Técnicas Antiforenses",
             "Perícias em Locais de Internet e relacionados à Pornografia Infanto-Juvenil",
             "Práticas Forenses: Elaboração de Laudos e Pareceres, e Assistência Técnica",
             "Criptografia e Criptoanálise",
             "Segurança e Inteligência Cibernética",
             "Perícias em Imagens Digitais",
         ],
     },
     {
         id: 4,
         course: "Postgraduate in Criminal Science and Forensic Sciences",
         startedAt: "2019",
         finishedAt: "2021",
         university: {
             name: "UNIT - Tiradentes University",
             url: "https://www.unit.br/",
         },
         researchLine: "Digital Chain of Custody",
         brand: "unit.png",
         curriculum: ["Local de Crime",
             "Medicina Legal",
             "Introdução à Criminalística",
             "Psicologia Forense",
             "Balística Forense",
             "Legislação aplicada à Criminalística",
             "Documentoscopia",
             "Papiloscopia",
             "Metodologia Científica",
             "Bombas, explosivos e combustíveis",
             "Biologia Forense",
             "Odontologia Forense",
             "Antropologia Forense",
             "Genética Forense",
             "Análise de drogas de abuso",
             "Perícia Ambiental",
             "Computação Forense",
             "Engenharia Forense",
             "Entomologia Forense",
             "Acidentes de Trânsito",
             "Toxicologia Forense",
             "Seminários de Conclusão",
             "Monografia",
         ],
     },
     {
         id: 5,
         course: "Master's Degree in Computer Science",
         startedAt: "2017",
         finishedAt: "2019",
         university: {
             name: "UFBA - Federal University of Bahia",
             url: "https://computacao.ufba.br/pt-br/programa-de-pos-graduacao-em-ciencia-da-computacao",
         },
         researchLine: "Recommender Systems",
         brand: "ufba.png",
         curriculum: ["Algoritmos e Grafos",
             "Seminários Científicos",
             "Fundamentos de Pesquisa em Ciência da Computação I",
             "Tópicos em Inteligência Computacional II",
             "Tópicos em Sistemas de Informação e WEB I",
             "Tópicos em Inteligência Computacional III",
             "Pesquisa Orientada",
             "Estágio Docente Orientado",
             "Projeto de Dissertação de Mestrado",
             "Defesa de Proposta de Mestrado",
             "Trabalho de Conclusão",
         ],
     },
     {
         id: 6,
         course: "MBA in Database Administration",
         startedAt: "2014",
         finishedAt: "2016",
         university: {
             name: "Fanese - Faculty of Business and Administration of Sergipe",
             url: "https://fanese.edu.br/",
         },
         researchLine: "Data Warehouse",
         brand: "fanese.png",
         curriculum: ["Fundamentos de Bancos de Dados",
             "Infraestrutura de Redes",
             "Infraestrutura de Sistemas Operacionais e Adm de Servidores",
             "Ética e Responsabilidade Socioambiental",
             "Relações Interpessoais",
             "Arquitetura e Administração de Banco de Dados I (SQL Server)",
             "Arquitetura e Administração de Banco de Dados II (Oracle)",
             "Procedimentos de Backup e Restauração I (SQL Server)",
             "Procedimentos de Backup e Restauração II (Oracle)",
             "Metodologia da Pesquisa Científica I",
             "Otimização de Aplicações para Banco de Dados",
             "Preparação Certificação (MCITP)",
             "Segurança e Auditoria em Bancos de Dados",
             "Arquitetura e Adm. de Banco de Dados III (PostgreSQL)",
             "Business Inteligence e DataWarehouse",
             "Data Mining (Mineração de Dados)",
             "Metodologia da Pesquisa Científica II",
             "Preparação para Certificação (OCA)",
             "Replicação e Alta Disponibilidade", "TCC",
         ],
     },
     {
         id: 7,
         course: "Web Systems",
         startedAt: "2112",
         finishedAt: "2014",
         university: {
             name: "UNIT - Tiradentes University",
             url: "https://www.unit.br/",
         },
         researchLine: "",
         brand: "unit.png",
         curriculum: ["Lógica Matemática",
             "Introdução à Informática",
             "Introdução à Programação Web",
             "Padrões Web",
             "Organização e Arquitetura de Computadores",
             "Metodologia Científica",
             "Práticas Investigativas I",
             "Engenharia de Software I",
             "Tecnologia Web",
             "Sistemas Operacionais",
             "Organização de Processos",
             "Práticas Extensionistas I",
             "Estrutura de Dados I",
             "Banco de Dados I",
             "Engenharia de Software Ii",
             "Tecnologia Web Ii",
             "Estrutura de Dados I",
             "Banco de Dados I",
             "Engenharia de Software Ii",
             "Redes de Computadores I",
             "Sistemas Operacionais",
             "Estrutura de Dados I",
             "Engenharia de Software Ii",
             "Segurança em Aplicações Web",
             "Gerência de Projetos",
             "Tópicos Especias (Optativa)",
             "Organização de Processos",
             "Estrutura de Dados Ii",
             "Tecnologia Web Iii",
             "Projeto Web I",
             "Projeto Web Ii",
             "Estágio em Desenvolvimento Web",
             "Projeto de Arquitetura De Aplicações",
         ],
     },
 ];
